# Generated by Django 4.2 on 2023-09-30 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=256, verbose_name='Name')),
                ('location', models.CharField(max_length=256, verbose_name='Location')),
                ('description', models.TextField(max_length=1000, verbose_name='Description')),
            ],
        ),
    ]
