# Generated by Django 4.2 on 2023-09-30 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attraction',
            old_name='description',
            new_name='content',
        ),
    ]
