# Generated by Django 4.2 on 2023-09-30 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0002_rename_description_attraction_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attraction',
            old_name='name',
            new_name='object_name',
        ),
    ]
