# Generated by Django 4.2 on 2023-09-30 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0004_alter_attraction_object_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='misataken_names',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
