# Generated by Django 4.2.6 on 2023-10-13 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0006_remove_attraction_misataken_names_misspellednames'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='audio',
            field=models.FileField(blank=True, upload_to='audio/'),
        ),
    ]
