# Generated by Django 4.2.6 on 2023-11-22 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0007_alter_attraction_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MisspelledNames',
        ),
    ]
