# Generated by Django 4.2.6 on 2023-10-14 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0007_attraction_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='audio',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
