# Generated by Django 4.2.6 on 2023-11-22 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0007_alter_attraction_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='object_name',
            field=models.CharField(db_index=True, max_length=256, verbose_name='Name'),
        ),
        migrations.AddConstraint(
            model_name='attraction',
            constraint=models.UniqueConstraint(fields=('object_name', 'location'), name='unique attraction'),
        ),
    ]
