# Generated by Django 4.2.6 on 2023-11-24 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0008_alter_attraction_object_name_and_more'),
        ('attractions', '0008_delete_misspellednames'),
    ]

    operations = [
    ]
