# Generated by Django 4.2.6 on 2023-10-17 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0009_alter_attraction_audio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attraction',
            name='audio',
        ),
    ]
